name: Mini DevSecOps CI

on:
  push:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Security scan with Bandit
        run: bandit -r . --exclude ./test_app.py

      - name: Build Docker image
        run: docker build -t devsecops-app .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devsecops-app'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
      